/* ─────────────────────────────────────────────────────────────────
   build-offsite.mjs — generate OFFSITE-SETUP.md from prices.mjs
   ─────────────────────────────────────────────────────────────────
   The hand-written version of that file was the single most dangerous
   document in the repo. Every text in it was marked "ready to paste",
   and every text in it named four clients that do not exist — Il Duca,
   SoYou Cosmetics, Eden Terranova, LeVallon — which had been removed
   from the site as fabricated three days after the file was last saved.
   It also quoted the July prices. Following it would have republished
   both onto Google, Sortlist and a journalist's inbox.

   So it is generated now. Prices come from prices.mjs; no client name
   can appear because none is defined anywhere in this script.

     node scripts/seo/build-offsite.mjs

   OFFSITE-SETUP.md stays gitignored: the GitHub mirror is public and
   this is outreach strategy.
   ───────────────────────────────────────────────────────────────── */
import { writeFileSync } from 'node:fs';
import { PRICES, CHF } from './prices.mjs';

const ROOT = 'C:/Users/Admin/Desktop/mulle-studio';
const P = {
  identity: CHF(PRICES.identity),
  vitrine: CHF(PRICES.vitrine),
  ecommerce: CHF(PRICES.ecommerce),
  monthly: CHF(Math.min(...Object.values(PRICES.marketing), ...Object.values(PRICES.growthOps))),
};

const md = `# Off-site setup — every text, generated from the live prices

> **Generated by \`scripts/seo/build-offsite.mjs\`. Do not hand-edit.**
> Change a price in \`scripts/seo/prices.mjs\` and re-run this.
>
> The previous hand-written version of this file offered every text below as
> "ready to paste", and each one named four clients that do not exist and quoted
> prices that had been cut. Pasting it would have put fabricated client work on
> Google, on Sortlist and in a journalist's inbox. That is why this is a
> generator: **no client name is defined anywhere in it, so none can appear.**

## The rule that governs every text here

Fritz has no delivered client mandates. The portfolio is self-initiated concept
work and is labelled as such. The founder's freelance track record is real and
may be described **as the founder's, before Fritz** — never as the agency's.

Never write, in any profile, post or email: a client name, "clients récents",
"ils nous font confiance", "trusted by", or a case study that implies delivery.

## Current prices — the only figures that may appear

| Engagement | Price |
|---|---|
| Identité de marque | ${P.identity} |
| Site vitrine | ${P.vitrine} |
| Site e-commerce | ${P.ecommerce} |
| Marketing (mensuel) | dès ${P.monthly}/mois |
| Growth Ops (mensuel) | dès ${P.monthly}/mois |

The three one-off engagements are **separate purchases**. Never write
"identité comprise", "Everything in…", or anything that reads as a ladder. The
monthly programmes do legitimately ladder; that is a different thing.

---

## 1. Google Business Profile — do this first

**Before you touch the form**, set the Google account to French and Switzerland.
The account defaults to Hebrew and the session geolocates to Israel, which will
otherwise steer the whole profile: myaccount.google.com/language → Français.

business.google.com → *Manage now*.

**Name** (exactly this, nothing appended — keyword-stuffed names get suspended)
\`\`\`
Agence Fritz
\`\`\`

**Primary category**
\`\`\`
Agence de marketing
\`\`\`

**Additional categories**
\`\`\`
Graphiste
Concepteur de sites web
Agence de publicité
\`\`\`

**Location**: choose *"Je livre des biens et services à mes clients"*, then
**hide the address**. There is no storefront and a home address should not be public.

**Service area**
\`\`\`
Genève (canton)
Vaud
Fribourg
Neuchâtel
Valais
\`\`\`

**Phone**: leave empty. A service-area profile does not require one, and no
number is published on the site by decision. Verification will be by video or
postcard rather than by call.

**Website**
\`\`\`
https://agencefritz.com
\`\`\`

**Description** (750 character limit)
\`\`\`
Fritz est un studio indépendant basé à Genève : marque, web et croissance. Identité de marque, sites vitrine et e-commerce, marketing et growth ops, conçus et pilotés par une seule personne, du cadrage à la mise en ligne.

Les prix sont publiés, par prestation distincte : identité de marque ${P.identity}, site vitrine ${P.vitrine}, e-commerce ${P.ecommerce}, en paiement unique. Marketing et growth ops dès ${P.monthly} par mois.

Le soin d'une agence, la structure d'un indépendant. Un seul interlocuteur, celui qui exécute. Le code et les fichiers sources sont livrés au client. Réponse sous 24 heures, devis gratuit.
\`\`\`

**Services**

| Service | Price |
|---|---|
| Identité de marque | ${P.identity} |
| Site vitrine | ${P.vitrine} |
| Site e-commerce | ${P.ecommerce} |
| Accompagnement marketing | dès ${P.monthly}/mois |
| Growth Ops | dès ${P.monthly}/mois |

**Photos** — 6 to 10. The studio and the desk, the wordmark, and screens of the
concept work that is already published on /fr/realisations. **No client work,
because there is none**, and no stock photography.

**Verification is mandatory.** An unverified profile does not appear at all.

---

## 2. Bing Webmaster Tools + Bing Places (10 min)

bing.com/webmasters → *Get started* → **Import from Google Search Console**,
authorising with the account that owns the property. The sitemap comes across
automatically.

Then **Bing Places**, importing from the Business Profile once it is verified.

Bing already ranks agencefritz.com first for "agence fritz genève" without any
of this, and Bing feeds ChatGPT search. It is ten minutes for real reach.

---

## 3. LinkedIn (20 min)

Your personal profile is still indexed under the pre-Fritz brand, so search
engines associate the site with a name that no longer exists. Fix the headline
first, then create the page.

**Personal headline**
\`\`\`
Designer indépendant · Agence Fritz, Genève — marque, web et croissance
\`\`\`

**Company page name**: \`Agence Fritz\` · **Tagline**
\`\`\`
Studio indépendant à Genève. Prix publiés.
\`\`\`

**About**
\`\`\`
Fritz est un studio de design indépendant à Genève : identité de marque, sites vitrine et e-commerce, marketing et growth ops.

Une seule personne conçoit, dessine et met en ligne — celle qui répond à votre premier message. Les prix sont publiés à l'avance, par prestation distincte : identité ${P.identity}, site vitrine ${P.vitrine}, e-commerce ${P.ecommerce}. Le code et les fichiers sources vous appartiennent.

Réponse sous 24 heures. agencefritz.com
\`\`\`

Link the page from the personal profile and the personal profile from the page.
Both URLs then go into \`SAME_AS\` in \`scripts/seo/stamp-org.mjs\`, so the site's
schema points at them.

---

## 4. Directories (six, about two hours across a week)

Use the exact string **Agence Fritz** and the website URL on every one. Both
Swiss directories already list unrelated people named Fritz, so an inexact name
merges the studio into that noise.

1. **Sortlist** (sortlist.ch, free) — the highest value of the six
2. **local.ch** — the main Swiss local directory
3. **search.ch** — second most used
4. **TechBehemoths** — free, agency-focused
5. **Clutch.co** — free profile
6. **DesignRush** — free tier

**Sortlist tagline**
\`\`\`
Le soin d'une agence, la structure d'un indépendant. Prix publiés.
\`\`\`

**Sortlist description**
\`\`\`
Fritz est un studio indépendant basé à Genève, actif dans toute la Suisse romande. Identité de marque, sites web et e-commerce, conçus et développés par la même personne, du cadrage à la mise en ligne.

Ce qui distingue le studio : des prix publiés à l'avance plutôt que des devis opaques (identité ${P.identity}, site vitrine ${P.vitrine}, e-commerce ${P.ecommerce}, paiement unique), un seul interlocuteur qui est aussi celui qui exécute, et la remise systématique du code et des fichiers sources au client.

Le studio travaille en français et en anglais.
\`\`\`

**Tags**: Web Design, Brand Identity, Logo Design, E-commerce, Graphic Design,
Web Development, SEO · **Budget minimum**: ${P.identity} · **Languages**: Français, English

**Portfolio**: the published concept work only, labelled *Concept*. Sortlist
allows platform reviews, which are not Google reviews and are in scope — but
only from real past clients of the founder's freelance practice, described as
such.

**NOT a directory**: lemeilleurduweb.ch is an annual Swiss web-design
competition. It belongs in the authority phase, entered with a real client
project, not filled in as a listing.

---

## 5. The warm note — the highest-value thing on this page

The founder's freelance practice has served 70+ businesses since 2019. Not one
of them has been told Fritz exists. These are existing business relationships,
so an individual note to each is not unsolicited mass advertising under LCD
art. 3 al. 1 let. o — but send them **one at a time from your own mailbox**,
never as a campaign.

Ten a day.

**French**
\`\`\`
Objet : Ce que je fais maintenant — Agence Fritz

Bonjour {Prénom},

Nous avons travaillé ensemble sur {le projet} en {année}. Je vous écris parce que j'ai depuis structuré mon activité en studio : Agence Fritz, à Genève.

Ce que ça change concrètement : je ne fais plus seulement le design, je livre l'ensemble — identité, site, et le suivi qui va avec. Les prix sont publiés, par prestation distincte : identité de marque ${P.identity}, site vitrine ${P.vitrine}, e-commerce ${P.ecommerce}. Toujours une seule personne du début à la fin, la même qu'avant.

Deux raisons de vous écrire : si vous avez un projet en tête, j'ai de la place ce trimestre. Et si vous connaissez quelqu'un qui cherche, une mise en relation vaut beaucoup pour un studio qui démarre.

Le site : https://agencefritz.com

Bien à vous,
{Nom}
\`\`\`

**English**
\`\`\`
Subject: What I'm doing now — Agence Fritz

Hello {First name},

We worked together on {the project} in {year}. I'm writing because I've since built the practice into a studio: Agence Fritz, in Geneva.

What that changes: I no longer just do the design, I deliver the whole thing — identity, website, and the follow-through. Prices are published, as separate engagements: brand identity ${P.identity}, website ${P.vitrine}, e-commerce ${P.ecommerce}. Still one person start to finish, the same one as before.

Two reasons to write: if you have something in mind, I have room this quarter. And if you know someone who is looking, an introduction is worth a great deal to a studio that is starting out.

The site: https://agencefritz.com

Best,
{Name}
\`\`\`

---

## 6. The first-client offer

To the five warmest names on that list, and to five from the outbound ledger.

\`\`\`
Pour le premier mandat Fritz, je propose 30 % sous le prix publié, en échange de trois choses : votre nom comme référence, deux phrases de retour que je puisse citer, et un crédit en pied de page qui renvoie vers agencefritz.com.

C'est une seule fois, et c'est dit franchement : un studio qui démarre a besoin d'une première référence réelle plus que de la marge.
\`\`\`

Write the three reference terms into the quote itself, not into a side
conversation. That credit link is also the best backlink available.

---

## 7. Agencies that subcontract

Ten individual notes to studios in Geneva, Lausanne and Lyon, offering
white-label production at the published prices. Same one-to-one rule as above:
specific, addressed to a person, never a list send.

\`\`\`
Objet : Production design en marque blanche — Genève

Bonjour,

Je dirige Agence Fritz, un studio indépendant à Genève. Je travaille aussi en marque blanche pour des agences qui ont plus de demande que de capacité : identité, site vitrine, e-commerce.

Les prix publiés sont ceux-ci — identité ${P.identity}, site vitrine ${P.vitrine}, e-commerce ${P.ecommerce} — et se négocient en volume. Une seule personne exécute, ce qui rend les délais prévisibles.

Si ça peut servir un jour, gardez mon adresse : https://agencefritz.com

Bien à vous,
{Nom}
\`\`\`

---

## 8. Listicle outreach

\`mister-wp.com\` publishes a Swiss web-agency listicle. Editor: **Mélanie
Dorval**, contact address published on the site. Send from your own address.

\`\`\`
Objet : Studio de design à Genève, prix publiés — pour votre sélection d'agences suisses

Bonjour Mélanie,

Je dirige un studio de design indépendant à Genève : identité de marque, sites web et e-commerce.

Je vous écris parce que votre sélection d'agences web suisses est une des rares références utiles sur le sujet, et parce que mon studio a une particularité qui pourrait intéresser vos lecteurs : je publie mes prix. Identité de marque ${P.identity}, site vitrine ${P.vitrine}, e-commerce ${P.ecommerce}, en paiement unique. C'est inhabituel sur ce marché, où presque tout se chiffre sur devis, et c'est précisément ce qui rend la comparaison difficile pour un dirigeant de PME.

Le studio est tenu par une seule personne : celle qui répond au premier message est celle qui dessine et qui code. Le code et les fichiers sources sont livrés au client à la fin du projet.

Le studio est jeune et je préfère le dire : les travaux publiés sont des projets d'initiative personnelle, présentés comme tels. Ce que je peux montrer, c'est la méthode et les prix.

Le site : https://agencefritz.com — et la page tarifs, si vous voulez vérifier que les prix sont bien publics : https://agencefritz.com/fr/tarifs

Si le format ne convient pas, aucun souci, et merci pour le travail que vous publiez.

Bien à vous,
{Nom}
Agence Fritz, Genève
\`\`\`

---

## What is already done

- Google Search Console: verified domain property, sitemap submitted and resubmitted
- The sitemap now carries a real modification date per page
- IndexNow: key file live, submission script in \`scripts/seo/indexnow.mjs\`
- Analytics and conversion events on every page (**Web Analytics still needs the
  dashboard toggle**; Speed Insights is already collecting)
- Contact form delivers to a database and an inbox, with a receipt to the sender
`;

writeFileSync(`${ROOT}/OFFSITE-SETUP.md`, md);

/* verification: the generator must not be able to emit a fabricated client or a
   superseded price, and it must not be committed to the public mirror. */
const BANNED = [/Il Duca/i, /SoYou/i, /Eden ?Terranova/i, /LeVallon/i, /clients? récents?/i,
  /CHF ?1'?200/, /CHF ?1'?400/, /CHF ?1'?700/, /CHF ?2'?200/, /CHF ?2'?500/, /CHF ?490/, /CHF ?2'?900/];

// Only the fenced blocks are checked: those are the texts that get pasted into
// Google, Sortlist and an email. The prose around them explains which phrases are
// forbidden and must be allowed to name them.
const pasteable = [...md.matchAll(/```([\s\S]*?)```/g)].map((m) => m[1]).join('\n');
const hits = BANNED.filter((re) => re.test(pasteable));
console.log(`OFFSITE-SETUP.md written · ${md.length} chars · prices ${P.identity} / ${P.vitrine} / ${P.ecommerce} / dès ${P.monthly}`);
if (hits.length) {
  console.log('FAIL: generated file contains ' + hits.map(String).join(', '));
  process.exitCode = 1;
} else {
  console.log('verified: no fabricated client, no superseded price');
}
